CREATE TABLE user_ (
  id CHAR(36) PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP
);

CREATE TABLE product_ (
  id CHAR(36) PRIMARY KEY,
  name_ VARCHAR(255) UNIQUE NOT NULL,
  price INT NOT NULL
);
