CREATE TABLE user_ (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP
);

CREATE TABLE product_ (
  id SERIAL PRIMARY KEY,
  name_ VARCHAR(255) UNIQUE NOT NULL,
  price INT NOT NULL
);
